version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: RASPLUS
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: senha123
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
